<?php

/**
 * return the resize definitions from the module.
 *
 * @return array<string, array{x: int, y: int, format: mixed[], path: string}> $resize_definition
 *
 * @throws Exception
 */
function getResizeDefinition(string $filename, string $path): array
{
}

?>
-----
<?php

/**
 * return the resize definitions from the module.
 *
 * @return array<string, array{x: int, y: int, format: mixed[], path: string}>
 *
 * @throws Exception
 */
function getResizeDefinition(string $filename, string $path): array
{
}

?>
